### ISSUE TITLE
Linter CLI ignores `excludes`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#149]
As pointed out by @dikmax in #148.

**Comment by pq** [comment]
@dikmax: what OS are you on?

Does quoting the exclude work better?
```
  exclude:
    - 'test/data/**'
```

Thanks!

**Comment by pq** [comment]
The source in question:
```
files:
  include:
    - 'bin/**'
    - 'lib/**'
    - 'test/**'
    - 'tool/**'
  exclude:
    - test/data/**
```

@dikmax reports:

> Still finds lint errors in test/data/*.dart
