### ISSUE TITLE
Have a way to enable _all_ lint rules _but_ a specific list

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/linter#1889]
Currently, all rules are disabled by default, and we have to enable each individual lint manually.

The problem is, on projects with a strict policy (that basically enables everything unless there's a specific reason not to), it becomes very difficult to read what is **not** enabled.

It would be incredibly more readable if we could do something like:

```yaml
linter:
  default: true
  rules:
    some_lint: false
```

Which would enable everything _but_ `some_lint`.

It would indeed, "break" when new lints are added. But that is voluntary. They are only warning anyway and don't prevent shipping the app this way.
But having the warnings ASAP, even if we don't fix them immediately, is very useful information.

**Comment by pq** [comment]
See also: https://github.com/dart-lang/linter/issues/1765.

Assuming we did that, it would look something like:

```yaml
include: package:linter/rules/all.yaml

linter:
  some_lint: false
```


> It would indeed "break" when new lints are added. But that is voluntary. 

[`package:pedantic`](https://github.com/dart-lang/pedantic) provides versioned rule lists (in addition to "latest") to address this issue.  Something similar could be considered here (if that use  case matters).  IOW something like:


```yaml
include: package:linter/rules/all_0.1.106.yaml

linter:
  some_lint: false
```
