### ISSUE TITLE
`sort_pub_dependencies` false positive

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2271]
Repro:

```yaml
name: animations
description: Fancy pre-built animations that can easily be integrated into any Flutter application.
version: 1.1.1
homepage: https://github.com/flutter/packages/tree/master/packages/animations

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: ^2.0.8
```

https://github.com/flutter/packages/blob/837b1a321d3f00034556ef5b385abb93c0843715/packages/animations/pubspec.yaml

See failure: https://cirrus-ci.com/task/5329170379046912

/fyi @dnfield
