### ISSUE TITLE
Empty rules section disables lints from include

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#2612]
Surprisingly, the following `analysis_options.yaml` file appears to be disabling all lints defined in the `include`.

```yaml
include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
```

Removing the linter/rules section altogether makes violations of lints from the include visible. So does uncommenting one of the lines in that section.
