### ISSUE TITLE
VSCode: '{avoid_print: false}' is not a recognized lint rule

### ISSUE THREAD

**Issue by larssn** [dart-lang/linter#2968]
**Describe the issue**
`avoid_print` is a real lint rule, but not recognized.

**To Reproduce**
I get this error with the following analysis_options.yaml file:

```
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    - use_rethrow_when_possible
    - avoid_print: false
```

**Expected behavior**
I expect it to respect me trying to turn off that lint. :-)

**Comment by bwilkerson** [comment]
I suspect that the issue is that you're mixing the list and map syntax in the YAML file. I believe that the syntax causes the name in the second list item to be "avoid_print: false". Does it work if the linter section looks like the following?
```yaml
linter:
  rules:
    use_rethrow_when_possible: true
    avoid_print: false
```
