### ISSUE TITLE
Unexpected behavior on `dart(prefer_const_declarations)` rule on Windows 10

### ISSUE THREAD

**Issue by lakscastro** [dart-lang/linter#3053]
**Describe the issue**

Analyzer don't trigger `dart(prefer_const_declarations)` on Windows if using `dart:math` on a declaration.

**Printscreens**

![image](https://user-images.githubusercontent.com/51419598/140029993-9d3caf84-afa9-40b8-a9ec-0c9f0fbf0d15.png)

![image](https://user-images.githubusercontent.com/51419598/140030060-f2f3c536-65f8-43c8-a6c5-f54dedeaa965.png)

**Examples**

```dart
import 'dart:math' as math;

void main() {
  /// Trigger `Prefer const over final for declarations.`  Working ✔️
  final a = 1 + 1;

  /// Don't trigger nothing even `math.pi` being a constant variable ❌
  /// Expected behavior: Trigger the rule `Prefer const over final for declarations.`
  final b = 1 + 1 + math.pi;
}
```

**Rule: `dart(prefer_const_declarations)`**

**To Reproduce**
Ideally, please include an example.

## [Reproducible Dart Project Zipped Folder](https://github.com/dart-lang/linter/files/7466248/dartpad.zip)

You can download the zipped project above or just create a project with the configuration described in this issue.

### Steps:

1. Install packages `dart pub get`
2. Open `lib/main.dart`

**Expected behavior**

The following:

```dart
final a = 1 + 1 + math.pi; 
```

Should trigger the `Prefer const over final for declarations.` rule because this is a constant declaration in a final declaration.

**Additional context**

### Flutter Context
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

### Linter Version and Reproducible Project Context

```yaml
name: dartpad
description: DartPad
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: "2.5.3"

dev_dependencies:
  flutter_lints: ^1.0.4
```

### Analysis Options

```yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
```
