### ISSUE TITLE
Is there any analysis_option to warn Map key type error

### ISSUE THREAD

**Issue by dikinova** [dart-lang/linter#3602]
// the key of the map should be int, so the second line is wrong. is there any analysis_option to warn this code error?
  Map<int, String> mb = {1: "1", 2: "2"};
  var xy = mb["abc"];

**Comment by incendial** [comment]
@dikinova hi, you can use `dart_code_metrics` package which has an `avoid-collection-methods-with-unrelated-types` rule https://dartcodemetrics.dev/docs/rules/common/avoid-collection-methods-with-unrelated-types

**Comment by dikinova** [comment]
Thanks!
but I install this package, and it has no effect?

```
dev_dependencies:
  dart_code_metrics: ^4.16.0
```

```
dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-collection-methods-with-unrelated-types:
        severity: error
```
