### ISSUE TITLE
Fail CI when lints are present

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#436]

**Comment by zoechi** [comment]
I guess this can be accomplished using

```
analyzer:
  errors:
    unused_local_variable: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
```

See also https://www.dartlang.org/guides/language/analysis-options
