### ISSUE TITLE
avoid_as with static cast

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/linter#663]
From docs:
> Note that an exception is made in the case of `dynamic` since the cast has no performance impact.

```yaml
analyzer:
  strong-mode:
    implicit-casts: False
    implicit-dynamic: False

linter:
  rules:
    - avoid_as
```

```dart
void main() {
  Object now = new DateTime.now();
  print((now as dynamic/*=DateTime*/).timeZoneName);
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
}
```
Since this code gives `avoid_as` warning, does it mean that such cast has performance impact?
